language: node_js
services:
  - postgresql
node_js:
  - "6"
before_install:
  - npm install -g sequelize-cli@2.8.0
  - npm install -g mocha
  - npm install codecov -g

before_script:
  - npm install
  - psql -c 'create database "HelloBooksTest";' -U postgres

script:
  - npm run test
  - npm run test:client

after_success:
  - npm install codeclimate-test-reporter -g
  - npm run coverage

addons:
  code_climate:
    repo_token: yss3uAPO4d37EcrMY4V9SNlRP8twCg0U4