
const hostUrl = 'http://localhost:8080'
export default {
  'Ensure all elements are present on home page display': function (browser) {
    browser
      .url(hostUrl)
      .resizeWindow(1700, 800)
      .maximizeWindow()
      .waitForElementVisible('body', 10000)
      .pause(1000)
      .assert.visible('.brand-logo.left.adjust')
      .assert.containsText('.brand-logo.left.adjust', 'HelloBooks')
      .assert.visible('input[type=search]')
      .assert.visible('input[placeholder="Title, Author, Keyword"]')      
      .setValue('input[type=search]', 'every')
      .keys(browser.Keys.ENTER)
      .back()
      .assert.containsText('a.dropdown-button', 'Hi, User')
      .moveToElement('a.dropdown-button', 30, 30)
      .pause(1000)
      .click('a.dropdown-button')
      .pause(1000)
      .assert.visible('li a')
      .assert.visible('li a', 'Sign Up')
      .moveToElement('#dropdown1', 20, 20)
      .click('#dropdown1 li a[href="/signup"]')
      .pause(2000)
      .assert.urlEquals(`${hostUrl}/signup`)
      .back()
      .moveToElement('a.dropdown-button', 30, 30)
      .pause(1000)
      .click('a.dropdown-button')
      .pause(1000)
      .assert.visible('li a')
      .assert.visible('li a', 'Sign In')
      .moveToElement('#dropdown1', 20, 20)
      .click('#dropdown1 li a[href="/signin"]')
      .assert.urlEquals(`${hostUrl}/signin`)
      .back()
      .moveToElement('.home-page-slider', 20, 20)
      .moveToElement('.slides', 20, 20)
      .moveToElement('ul li', 20, 20)
      .assert.attributeContains('img', 'alt', 'sliderimage1')
      .assert.visible('div h4 span', 'Most Popular BOOKS')
      .assert.visible('.book')
      .assert.visible('.card')
      .assert.visible('.card-image')
      .assert.visible('.card-content p', 'Details')
      .moveToElement('.card-content p', 20, 20)
      .click('.test-btn')
      .pause(3000)
      .assert.urlEquals(`${hostUrl}/signin`)
      .back()
      .moveToElement('.container', 20, 20)
      .assert.visible('.book-info')
      .assert.visible('.book-title span', 'Blink')
      .assert.visible('.book-author span', 'by Malcolm Gladwell')
      .moveToElement('.section.similar', 20, 20)
      .assert.containsText('.section.similar h3', 'Based on readers favorites')
      .assert.visible('.carousel')
      .assert.visible('.section.similar','indicators')
      .pause(500)
  }
};